name: "fmmel"
description: "Software to control Mitsubishi Ecodan"
version: "1.1.0"
slug: "mitsubishi_ecodan"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  5000/tcp: 5000